tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "wget"
brew "mas"
brew "git"
brew "git-lfs"
brew "tig"
brew "fish"
brew "fzf"

cask "google-chrome"
cask "google-japanese-ime"
cask "authy"
cask "visual-studio-code"
cask "deepl"
cask "slack"